version: '3.8'

services:
  frontend_pos:
    image: ${FRONT_POS_IMAGE}
    container_name: frontendPos
    restart: always
    networks:
      - app-net

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: coffeflash
      POSTGRES_USER: coffeadmin
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    image: nginx:stable_alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend_pos
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge

