spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/postgres
    url: jdbc:postgresql://postgres:5432/
    username: coffeadmin
    password: T5ZTz28huh
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false

  sql:
    init:
      mode: never
      continue-on-error: false

  liquibase:
    change-log: classpath:/liquibase/master-main.yml
    enabled: true

security:
  jwt:
    secret: c2ZBJUAjZndFZ2Yyd21uZm9qMTIzb2pmOGozNTFoZm5xMjNuZjkx
    access: 3600000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false

tenant:
  db-url-template: jdbc:postgresql://postgres:5432/{db}

logging:
  level:
    root: info

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}