spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testBD
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true

  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql


security:
  jwt:
    secret: c2ZBJUAjZndFZ2Yyd21uZm9qMTIzb2pmOGozNTFoZm5xMjNuZjkx
    access: 3600000
    refresh: 2592000000